[DllInjector]
AllowMultipleInstancesOfDLLInjector = 0
UseFullPathsFromIni = 1

# Exe to start
Exe = {0}
CommandLine = {1}

# Dll to inject
Dll = {2}

# Export to call in dll
Export = Init

# Check if call to export returned positive value
CheckReturnValue = 0

# Terminate the process when an error is sent from the injected dll
TerminateOnError = 1

# Wait for started exe to close before exiting the DllInjector process.
WaitForProcessTermination = 0

# Set a fake parent process
EnableFakeParentProcess = {3}
FakeParentProcess = explorer.exe

# Number to files to create
CreateFiles = {4}

# Name of the file(s) to create
FileToCreate_1 = {5}
FileToCreate_2 = {6}

#Patch an x86 exe to enable IMAGE_FILE_LARGE_ADDRESS_AWARE
Use4GBPatch = 0
FileToPatch_1 = 

BootImage = 
BootImageWidth = 0
BootImageHeight = 0